// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgwusowaizhrefljfsyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnd3Vzb3dhaXpocmVmbGpmc3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDkxNTcsImV4cCI6MjA2OTIyNTE1N30.ZAFpsGTVWgy8lLzoVHNbG5CkRyb3bbx3A3lgVzzcyBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});